
tr:
  title: "Bilgisayar Mühendisliği"
  languageName: Türkçe
  copyright: Telif hakkı © {year} Bilgisayar Mühendisliği Bölümü, Boğaziçi Üniversitesi. Tüm hakları saklıdır.
  weight: 1
  params:
    head:
      tagline: "Boğaziçi Üniversitesi"

en:
  title: "Computer Engineering"
  languageName: English
  copyright: Copyright © {year} Department of Computer Engineering, Boğaziçi University. All rights reserved.
  weight: 2
  params:
    head:
      tagline: "Boğaziçi University"
