main:
  - name: About
    url: /about/
    identifier: about
    weight: 100

  - name: People
    url: /people/
    identifier: people
    weight: 200
  - name: Faculty
    url: /people/faculty
    parent: people
    identifier: faculty
    weight: 201
  - name: Academic Staff
    url: /people/academic-staff
    parent: people
    identifier: academic-staff
    weight: 202
  - name: Support Staff
    url: /people/support-staff
    parent: people
    identifier: support-staff
    weight: 203
  # - name: Students
  #   url: /people/students
  #   parent: people
  #   identifier: students
  #   weight: 204

  - name: Undergraduate
    url: /undergraduate/
    identifier: undergraduate
    weight: 300
  - name: Program Overview
    url: /undergraduate/overview
    parent: undergraduate
    identifier: undergraduate-overview
    weight: 301
  - name: Curriculum
    url: /undergraduate/curriculum
    parent: undergraduate
    identifier: undergraduate-curriculum
    weight: 302
  # - name: Course List
  #   url: /undergraduate/courses
  #   parent: undergraduate
  #   identifier: undergraduate-courses
  #   weight: 303
  - name: Elective Courses
    url: /undergraduate/electives
    parent: undergraduate
    identifier: undergraduate-electives
    weight: 304
  - name: Double Major Programs
    url: /undergraduate/double-major
    parent: undergraduate
    identifier: undergraduate-double-major
    weight: 305
  - name: Minor Degree Programs
    url: /undergraduate/minor-degree
    parent: undergraduate
    identifier: undergraduate-minor-degree
    weight: 306
  - name: Exchange Programs
    url: /undergraduate/exchange
    parent: undergraduate
    identifier: undergraduate-exchange
    weight: 307
  - name: Industrial Training
    url: /undergraduate/training
    parent: undergraduate
    identifier: undergraduate-training
    weight: 308
  - name: Senior Projects
    url: /undergraduate/senior-projects
    parent: undergraduate
    identifier: undergraduate-senior-projects
    weight: 309
  - name: Graduation
    url: /undergraduate/graduation
    parent: undergraduate
    identifier: undergraduate-graduation
    weight: 310

  - name: Graduate
    url: /graduate/
    identifier: graduate
    weight: 400
  - name: PhD Program Overview
    url: /graduate/phd-program
    parent: graduate
    identifier: graduate-phd-program
    weight: 411
  - name: MS Program Overview
    url: /graduate/ms-program
    parent: graduate
    identifier: graduate-ms-program
    weight: 412
  - name: Other Affiliated Programs
    url: /graduate/affiliated-programs
    parent: graduate
    identifier: graduate-affiliated
    weight: 413

  - name: Courses
    url: /courses/
    identifier: courses
    weight: 500

  - name: Research
    url: /research/
    identifier: research
    weight: 600

  - name: Docs
    url: /docs/
    identifier: docs
    weight: 700
