backend:
  name: github
  repo: bouncmpe/bouncmpe.github.io
  branch: main
  base_url: https://bouncmpe.pages.dev
  auth_endpoint: /api/auth
  squash_merges: true
  open_authoring: true
  commit_messages:
    create: "content({{collection}}): create {{slug}}"
    update: "content({{collection}}): update {{slug}}"
    delete: "content({{collection}}): delete {{slug}}"
    uploadMedia: "media: upload media {{path}}"
    deleteMedia: "media: upload media {{path}}"
    open_authoring: "open-authoring: {{message}} by {{author-login}}"

local_backend: true
publish_mode: editorial_workflow

site_url: https://bouncmpe.pages.dev
logo_url: https://bouncmpe.pages.dev/images/logo.svg

media_folder: /assets/uploads
public_folder: uploads

slug:
  encoding: "ascii"
  clean_accents: true

i18n:
  structure: multiple_files
  locales: [en, tr]
  default_locale: en

theme:
  mode: dark

collections:
  - name: phd-thesis-defense
    label: PhD Thesis Defenses
    label_singular: PhD Thesis Defense
    identifier_field: name
    folder: content/events
    slug: "{{fields.datetime}}-{{name}}"
    path: "{{slug}}/index"
    summary: "PhD Thesis Defense by {{name}} on {{fields.datetime | date('MMMM D, YYYY @HH:mm')}}"
    create: true
    i18n: true
    editor:
      preview: false
    sortable_fields: ["fields.datetime", "name"]
    filter: { field: "type", value: "phd-thesis-defense" }
    fields:
      - label: Type
        name: type
        widget: hidden
        default: phd-thesis-defense
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Speaker Name
        name: name
        widget: string
        i18n: duplicate
      - label: Date and Time
        name: datetime
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: HH:mm:00
        i18n: duplicate
      - label: Duration
        name: duration
        widget: select
        options:
        - { label: "30 mins", value: "30m" }
        - { label: "1 hour", value: "1h" }
        - { label: "2 hours", value: "2h" }
        - { label: "3 hours", value: "3h" }
        - { label: "4 hours", value: "4h" }
        default: "2h"
        i18n: duplicate
      - label: Location
        name: location
        widget: string
        i18n: duplicate
        default: Ali Vahit Şahiner (AVŞ)

  - name: ms-thesis-defense
    label: MS Thesis Defenses
    label_singular: MS Thesis Defense
    identifier_field: name
    folder: content/events
    slug: "{{fields.datetime}}-{{name}}"
    path: "{{slug}}/index"
    summary: "MS Thesis Defense by {{name}} on {{fields.datetime | date('MMMM D, YYYY @HH:mm')}}"
    create: true
    i18n: true
    editor:
      preview: false
    sortable_fields: ["fields.datetime", "name"]
    filter: { field: "type", value: "ms-thesis-defense" }
    fields:
      - label: Type
        name: type
        widget: hidden
        default: ms-thesis-defense
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Speaker Name
        name: name
        widget: string
        i18n: duplicate
      - label: Date
        name: datetime
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: HH:mm:00
        i18n: duplicate
      - label: Duration
        name: duration
        widget: select
        options:
        - { label: "30 mins", value: "30m" }
        - { label: "1 hour", value: "1h" }
        - { label: "2 hours", value: "2h" }
        - { label: "3 hours", value: "3h" }
        - { label: "4 hours", value: "4h" }
        default: "1h"
        i18n: duplicate
      - label: Location
        name: location
        widget: string
        i18n: duplicate
        default: Ali Vahit Şahiner (AVŞ)

  - name: seminar
    label: Seminars
    label_singular: Seminar
    identifier_field: name
    folder: content/events
    slug: "{{fields.datetime}}-{{name}}"
    path: "{{slug}}/index"
    summary: "Seminar by {{name}} on {{fields.datetime | date('MMMM D, YYYY @HH:mm')}}"
    create: true
    i18n: true
    editor:
      preview: false
    sortable_fields: ["fields.datetime", "name"]
    filter: { field: "type", value: "seminar" }
    fields:
      - label: Type
        name: type
        widget: hidden
        default: seminar
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Speaker Name
        name: name
        widget: string
        i18n: duplicate
      - label: Date
        name: datetime
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: HH:mm:00
        i18n: duplicate
      - label: Duration
        name: duration
        widget: select
        options:
        - { label: "30 mins", value: "30m" }
        - { label: "1 hour", value: "1h" }
        - { label: "2 hours", value: "2h" }
        - { label: "3 hours", value: "3h" }
        - { label: "4 hours", value: "4h" }
        default: "1h"
        i18n: duplicate
      - label: Location
        name: location
        widget: string
        i18n: duplicate
        default: Ali Vahit Şahiner (AVŞ)

  - name: Stories
    label: Stories
    label_singular: Story
    folder: "content/news"
    identifier_field: title
    slug: "{{year}}-{{month}}-{{day}}-news-{{slug}}"
    path: "{{slug}}/index"
    media_folder: /assets/uploads
    public_folder: uploads
    create: true
    i18n: true
    editor:
      preview: false
    filter: { field: "type", value: "news" }
    fields:
      - label: Type
        name: type
        widget: hidden
        default: news
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Description
        name: description
        widget: string
        i18n: true
        required: false
      - label: Featured
        name: featured
        i18n: duplicate
        widget: boolean
        default: false
      - label: Publish Date
        name: date
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        format: YYYY-MM-DD
        i18n: duplicate
      - label: Thumbnail
        name: thumbnail
        widget: image
        allow_multiple: false
        i18n: duplicate
        required: false
        hint: >-
          You may use [**Adobe Express Resizer**](https://www.adobe.com/express/feature/image/resize) for resizing images.
          Use a 16:9 aspect ratio image for best results. Recommended size is 1280x720 pixels.
      - label: Text Body
        name: body
        widget: markdown
        default: ""
        i18n: true

  - name: special
    label: Special Events
    label_singular: Special Event
    identifier_field: name
    folder: content/events
    slug: "{{fields.datetime}}-{{name}}"
    path: "{{slug}}/index"
    summary: "{{title}} by {{name}} on {{fields.datetime | date('MMMM D, YYYY @HH:mm')}}"
    create: true
    i18n: true
    editor:
      preview: false
    sortable_fields: ["fields.datetime", "name"]
    filter: { field: "type", value: "special-event" }
    fields:
      - label: Type
        name: type
        widget: hidden
        default: special-event
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Organizer Name
        name: name
        widget: string
        i18n: true
      - label: Date
        name: datetime
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: HH:mm:00
        i18n: duplicate
      - label: Duration
        name: duration
        widget: select
        options:
        - { label: "30 mins", value: "30m" }
        - { label: "1 hour", value: "1h" }
        - { label: "2 hours", value: "2h" }
        - { label: "3 hours", value: "3h" }
        - { label: "4 hours", value: "4h" }
        default: "2h"
        i18n: duplicate
      - label: Location
        name: location
        widget: string
        i18n: duplicate
